version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: ./srcs/.env
    volumes:
      - /home/bruno/data/db:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: ./srcs/.env
    volumes:
      - /home/bruno/data/wp:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: ./srcs/.env
    ports:
      - "443:443"
    volumes:
      - /home/bruno/data/wp:/var/www/html:ro
      - ssl_certs:/etc/nginx/ssl:ro
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

volumes:
  ssl_certs:

networks:
  inception:
    driver: bridge
