version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes: []
      #- /home/bruno/data/db:/var/lib/mysql
    networks:
      - inception
    restart: always
    ports:
      - 3306

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wp_files:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    command: ["setup-wordpress.sh", "php-fpm7.4", "-F"]

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - /home/bruno/data/wp:/var/www/html:ro
      - ssl_certs:/etc/nginx/ssl:ro
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

volumes:
  ssl_certs:
  wp_files:

networks:
  inception:
    driver: bridge
